# Generated by Django 5.1.7 on 2026-04-17 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='max_occupancy',
        ),
    ]
