# Generated by Django 5.1.7 on 2026-04-17 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_org_id_event_org_alter_event_capacity_and_more'),
        ('events', '0002_remove_venue_max_occupancy'),
    ]

    operations = [
    ]
