# Generated by Django 6.0.4 on 2026-04-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('type', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
