# Generated by Django 6.0.4 on 2026-04-09 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_superuser'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='role',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('student_num', 'org')},
        ),
    ]
