# Generated by Django 6.0.4 on 2026-04-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_remove_event_org_id_event_org_alter_event_capacity_and_more'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_id', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purpose', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('request_date', models.DateField()),
                ('org_id', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='budget_requests', to='organizations.organization')),
            ],
            options={
                'db_table': 'budget_request',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('serial_number', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=50)),
                ('org_id', models.ForeignKey(db_column='org_id', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='organizations.organization')),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='EventEquipment',
            fields=[
                ('event_equip_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('assigned_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.ForeignKey(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_equipments', to='events.event')),
                ('item_id', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, related_name='event_equipments', to='finances.equipment')),
            ],
            options={
                'db_table': 'event_equipment',
            },
        ),
    ]
